"""Added tags column

Revision ID: ac41f625dc77
Revises: ce1efd272b31
Create Date: 2025-07-02 00:05:33.790605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac41f625dc77'
down_revision = 'ce1efd272b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table('engagement_metrics', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagement_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
