"""Added tags column

Revision ID: ce1efd272b31
Revises: 
Create Date: 2025-07-01 23:59:40.812981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1efd272b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagement_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagement_metrics', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
