DATABASE_URL="postgresql://postgres.eivvjtpbpmaikxckcrzp:pgadmin4@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres"
SECRET_KEY="my_super_secret_key"
YOUTUBE_API_KEY="AIzaSyCVq1Y2zGdeTdREjwwIC6hcz0Tx508xbz"
YOUTUBE_RATE_LIMIT_DELAY="2.0"
MAX_RESULTS_PER_SEARCH="10"
CLIENT_ID="usyeVrfBngTaAWy7N8s8Eg"
CLIENT_SECRET="dnf9qTZmjxEtOltzPjTt5SHEjGNiDw"
USER_AGENT= "EduAnalytScraper/0.1 by u/Sudden_Cockroach9150"
LOG_LEVEL="INFO"